collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0
  brandStrength: 0
  lightness: 0.4382979
  brandColors:
    - '#303030'
    - '#FBFBFB'
    - '#CFCFCF'
    - '#9A9A9A'
  rhythmicContrast: 0.887234
typography_spectrum: 0.7319149
layout_spectrum: 1
name: zeroinfinity
